# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'englishchatapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKPlacesKit'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # Pods for englishchatapp

  target 'englishchatapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'englishchatappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'englishchatapp-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for englishchatapp-tvOS

#   target 'englishchatapp-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
