export const CLIENT_ID = '4VMVDF0DJLP4DKSFNW210VFMEL1OJ3P5HAAQJGOC4YFYIOJ2';
export const CLIENT_SECRET = 'ZXA5FEE4GJY4S525PBWUDM22R3FTNTOHKQ0FMJNV0GGBTYBU';
export const FOURSQUARE_ENDPOINT = 'https://api.foursquare.com/v2/venues/explore';
export const API_DEBOUNCE_TIME = 2000;